name: islamic_app
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 11.0.0+1
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  get: ^4.6.5
  geolocator: ^9.0.2
  intl: ^0.17.0
  adhan: ^2.0.0-nullsafety.2
  flutter_svg: ^2.0.4
  permission_handler: ^10.3.0
  animated_custom_dropdown: ^1.2.2
  flutter_qiblah: ^2.1.0
  flutter_screenutil: ^5.9.0
  share_plus: ^4.5.3
  hijri: ^3.0.0
  awesome_dialog: ^3.0.2
  persistent_bottom_nav_bar_v2: ^5.3.0
  flutter_staggered_animations: ^1.1.1
  pdfx: ^2.5.0
  just_audio: ^0.9.34
  google_mobile_ads: ^5.1.0
  just_audio_background: ^0.0.1-beta.10
  rxdart: ^0.27.2
  awesome_notifications: ^0.7.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
    - assets/json/names_allah.json
    - assets/json/athkar.json
    - assets/json/hadith_nawawi.json
    - assets/pdf/quran.pdf
    - assets/json/quran_clean.json
    - assets/json/tafsir.json

  fonts:
    - family: othmani
      fonts:
        - asset: assets/fonts/HafsSmart_08.ttf
    - family: Noor
      fonts:
        - asset: assets/fonts/Noor-Bold.ttf
          
        - asset: assets/fonts/Noor-Regular.ttf
          
        - asset: assets/fonts/Noor-Light.ttf
          
